#ifndef CLOSEDCAPTIONTRACKINFO_H
#define CLOSEDCAPTIONTRACKINFO_H

#include <QObject>
#include <QUrl>
#include "language.h"

class ClosedCaptionTrackInfo
{
public:
    ClosedCaptionTrackInfo(QUrl url, Language language, bool isAutoGenerated)
        : m_url(url), m_language(language), m_isAutoGenerated(isAutoGenerated) {}

    /**
     * @brief Manifest URL of the associated track
     */
    QUrl url() const { return m_url; }

    /**
     * @brief Language of the associated track.
     */
    Language language() const { return m_language; }

    /**
     * @brief Whether the associated track was automatically generated
     */
    bool isAutoGenerated() const { return m_isAutoGenerated; }

    QString toString() const { return m_language.toString(); }

private:
    QUrl m_url;
    Language m_language;
    bool m_isAutoGenerated;
};

#endif // CLOSEDCAPTIONTRACKINFO_H
