set(QYTLIB_HEADERS_DIR "${CMAKE_CURRENT_LIST_DIR}/../include")

file(GLOB QYTLIB_COMMON_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/common/*.h")
file(GLOB QYTLIB_REVENG_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/reverseengineering/*.h")
file(GLOB QYTLIB_CIPHER_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/reverseengineering/cipher/*.h")
file(GLOB QYTLIB_RESPONSE_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/reverseengineering/responses/*.h")
file(GLOB QYTLIB_UTIL_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/utils/*.h")
file(GLOB QYTLIB_VIDEO_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/videos/*.h")
file(GLOB QYTLIB_CC_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/videos/closedcaptions/*.h")
file(GLOB QYTLIB_STREAM_HEADERS "${QYTLIB_HEADERS_DIR}/qytlib/videos/streams/*.h")

set(QYTLIB_HEADERS
  ${QYTLIB_COMMON_HEADERS}
  ${QYTLIB_REVENG_HEADERS}
  ${QYTLIB_CIPHER_HEADERS}
  ${QYTLIB_RESPONSE_HEADERS}
  ${QYTLIB_UTIL_HEADERS}
  ${QYTLIB_VIDEO_HEADERS}
  ${QYTLIB_CC_HEADERS}
  ${QYTLIB_STREAM_HEADERS}
)